/*
BSD 2-Clause License

Copyright (c) 2019, Beigesoft™
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.beigesoft.fct;

import java.util.Map;
import java.util.HashMap;

import org.beigesoft.exc.ExcCode;
import org.beigesoft.mdl.IHasId;
import org.beigesoft.hld.HldFldCls;
import org.beigesoft.hld.HldGets;
import org.beigesoft.hld.HldSets;
import org.beigesoft.hld.HldCnvFdCv;
import org.beigesoft.hld.HldNmFilFdRs;
import org.beigesoft.hld.HldNmFilFdSt;
import org.beigesoft.hld.HldFilFdCv;
import org.beigesoft.hld.HldNmCnFrRs;
import org.beigesoft.hld.HldNmCnFrSt;
import org.beigesoft.hld.HldNmCnToSt;
import org.beigesoft.hld.HldNmCnToStXml;
import org.beigesoft.hld.HldNmCnFrStXml;
import org.beigesoft.hnd.HndI18nRq;
import org.beigesoft.prp.UtlPrp;
import org.beigesoft.prp.Setng;
import org.beigesoft.log.ILog;
import org.beigesoft.cnv.FilEntRs;
import org.beigesoft.cnv.FilEntRq;
import org.beigesoft.cnv.FilCvEnt;
import org.beigesoft.rpl.RpEntWriXml;
import org.beigesoft.rpl.RpEntReadXml;
import org.beigesoft.rdb.IRdb;
import org.beigesoft.rdb.Orm;
import org.beigesoft.rdb.IOrm;
import org.beigesoft.rdb.ISqlQu;
import org.beigesoft.rdb.SqlQu;
import org.beigesoft.rdb.SrvClVl;
import org.beigesoft.srv.INumStr;
import org.beigesoft.srv.NumStr;
import org.beigesoft.srv.IReflect;
import org.beigesoft.srv.Reflect;
import org.beigesoft.srv.UtlXml;
import org.beigesoft.srv.IUtlXml;
import org.beigesoft.srv.ISqlEsc;
import org.beigesoft.srv.SqlEsc;

/**
 * <p>Main application beans factory. All configuration dependent inner
 * factories must be inside "fctConf".</p>
 *
 * @param <RS> platform dependent RDBMS recordset
 * @author Yury Demidenko
 */
public class FctBlc<RS> implements IFctApp {

  /**
   * <p>UVD holder field fillers names name.</p>
   **/
  public static final String HLFILFDNMUVD = "hlFiFdNmUvd";

  /**
   * <p>DB-Copy holder field fillers names name.</p>
   **/
  public static final String HLFILFDNMDBCP = "hlFiFdNmDbCp";

  /**
   * <p>DB-Copy entity writer service name.</p>
   **/
  public static final String ENWRDBCPNM = "enWrDbCp";

  /**
   * <p>DB-Copy entity reader service name.</p>
   **/
  public static final String ENRDDBCPNM = "enRdDbCp";

  /**
   * <p>DB-Copy Setting service name.</p>
   **/
  public static final String STGDBCPNM = "stgDbCp";

  /**
   * <p>UVD Setting service name.</p>
   **/
  public static final String STGUVDNM = "stgUvd";

  /**
   * <p>ORM Setting service name.</p>
   **/
  public static final String STGORMNM = "stgOrm";

  /**
   * <p>Standard logger name.</p>
   **/
  public static final String LOGSTDNM = "logStd";

  /**
   * <p>Secure logger name.</p>
   **/
  public static final String LOGSECNM = "logSec";

  //configuration data:
  /**
   * <p>Database full copy setting base dir.</p>
   **/
  private String stgDbCpDir;

  /**
   * <p>UVD setting base dir.</p>
   **/
  private String stgUvdDir;

  /**
   * <p>ORM setting base dir.</p>
   **/
  private String stgOrmDir;

  /**
   * <p>Android configuration, RDB insert returns autogenerated ID,
   * updating with expression like "VER=VER+1" is not possible.</p>
   **/
  private boolean isAndr = false;

  /**
   * <p>New database ID.</p>
   **/
  private int newDbId = 1;

  //parts/services:
  /**
   * <p>Outside app-beans/parts factory final configuration.
   * It must throws exception if bean not found. It may consist of
   * sub-factories. It puts its beans into this main factory beans.</p>
   **/
  private IFctAux fctConf;

    //cached services/parts:
  /**
   * <p>Logger.</p>
   **/
  private ILog logStd;

  //requested beans map, it's filled by this and external factories,
  //it's for high performance:
  /**
   * <p>Beans map.</p>
   **/
  private final Map<String, Object> beans = new HashMap<String, Object>();

  /**
   * <p>Get bean in lazy mode (if bean is null then initialize it).</p>
   * @param pRqVs request scoped vars
   * @param pBnNm - bean name
   * @return Object - requested bean or exception if not found
   * @throws Exception - an exception
   */
  @Override
  public final Object laz(final Map<String, Object> pRqVs,
    final String pBnNm) throws Exception {
    if (pBnNm == null) {
      throw new ExcCode(ExcCode.WRPR, "Null bean name!!!");
    }
    Object rz = this.beans.get(pBnNm);
    if (rz == null) {
      synchronized (this) {
        rz = this.beans.get(pBnNm);
        if (rz == null) {
          if (HndI18nRq.class.getSimpleName().equals(pBnNm)) {
            rz = lazHndI18nRq(pRqVs);
          } else if (STGORMNM.equals(pBnNm)) {
            rz = lazStgOrm(pRqVs);
          } else if (IOrm.class.getSimpleName().equals(pBnNm)) {
            rz = lazOrm(pRqVs);
          } else if (SrvClVl.class.getSimpleName().equals(pBnNm)) {
            rz = lazSrvClVl(pRqVs);
          } else if (ISqlQu.class.getSimpleName().equals(pBnNm)) {
            rz = lazSqlQu(pRqVs);
          } else if (FilCvEnt.class.getSimpleName().equals(pBnNm)) {
            rz = lazFilCvEnt(pRqVs);
          } else if (FilEntRs.class.getSimpleName().equals(pBnNm)) {
            rz = lazFilEntRs(pRqVs);
          } else if (HldCnvFdCv.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldCnvFdCv(pRqVs);
          } else if (HldNmFilFdRs.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmFilFdRs(pRqVs);
          } else if (HldFilFdCv.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldFilFdCv(pRqVs);
          } else if (HldNmCnFrRs.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmCnFrRs(pRqVs);
          } else if (FctCnvCv.class.getSimpleName().equals(pBnNm)) {
            rz = lazFctCnvCv(pRqVs);
          } else if (FctNmCnFrRs.class.getSimpleName().equals(pBnNm)) {
            rz = lazFctNmCnFrRs(pRqVs);
          } else if (FilEntRq.class.getSimpleName().equals(pBnNm)) {
            rz = lazFilEntRq(pRqVs);
          } else if (ENWRDBCPNM.equals(pBnNm)) {
            rz = lazRpEntWriXmlDbCp(pRqVs);
          } else if (ENRDDBCPNM.equals(pBnNm)) {
            rz = lazRpEntReadXmlDbCp(pRqVs);
          } else if (STGDBCPNM.equals(pBnNm)) {
            rz = lazStgDbCp(pRqVs);
          } else if (STGUVDNM.equals(pBnNm)) {
            rz = lazStgUvd(pRqVs);
          } else if (FctNmCnFrSt.class.getSimpleName().equals(pBnNm)) {
            rz = lazFctNmCnFrSt(pRqVs);
          } else if (FctNmFilFdSt.class.getSimpleName().equals(pBnNm)) {
            rz = lazFctNmFilFd(pRqVs);
          } else if (FctNmCnToSt.class.getSimpleName().equals(pBnNm)) {
            rz = lazFctNmCnToSt(pRqVs);
          } else if (HLFILFDNMUVD.equals(pBnNm)) {
            rz = lazHldNmFilFdStUvd(pRqVs);
          } else if (HLFILFDNMDBCP.equals(pBnNm)) {
            rz = lazHldNmFilFdStDbCp(pRqVs);
          } else if (HldNmCnToStXml.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmCnToStXml(pRqVs);
          } else if (HldNmCnFrStXml.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmCnFrStXml(pRqVs);
          } else if (HldNmCnFrSt.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmCnFrSt(pRqVs);
          } else if (HldNmCnToSt.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldNmCnToSt(pRqVs);
          } else if (HldGets.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldGets(pRqVs);
          } else if (HldSets.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldSets(pRqVs);
          } else if (HldFldCls.class.getSimpleName().equals(pBnNm)) {
            rz = lazHldFldCls(pRqVs);
          } else if (FctFctEnt.class.getSimpleName().equals(pBnNm)) {
            //IT DEPENDS OF ORM!
            rz = lazFctFctEnt(pRqVs);
          } else if (UtlPrp.class.getSimpleName().equals(pBnNm)) {
            rz = lazUtlPrp(pRqVs);
          } else if (INumStr.class.getSimpleName().equals(pBnNm)) {
            rz = lazNumStr(pRqVs);
          } else if (ISqlEsc.class.getSimpleName().equals(pBnNm)) {
            rz = lazSqlEsc(pRqVs);
          } else if (IUtlXml.class.getSimpleName().equals(pBnNm)) {
            rz = lazUtlXml(pRqVs);
          } else if (IReflect.class.getSimpleName().equals(pBnNm)) {
            rz = lazReflect(pRqVs);
          } else {
            rz = this.fctConf.crePut(pRqVs, pBnNm, this);
          }
        }
      }
    }
    return rz;
  }

  /**
   * <p>Puts beans by external AUX factory.</p>
   * @param pRqVs request scoped vars
   * @param pBnNm - bean name
   * @param pBean - bean
   * @throws Exception - an exception, e.g. if bean exists
   **/
  @Override
  public final synchronized void put(final Map<String, Object> pRqVs,
    final String pBnNm, final Object pBean) throws Exception {
    if (pBnNm == null || pBean == null) {
      throw new ExcCode(ExcCode.WRPR, "Null bean or name: nm/bn"
        + pBnNm + "/" + pBean);
    }
    if (this.beans.keySet().contains(pBnNm)) {
      throw new ExcCode(ExcCode.WRPR, "Bean exists: " + pBnNm);
    }
    this.beans.put(pBnNm, pBean);
  }

  /**
   * <p>Release beans (memory). This is "memory friendly" factory.</p>
   * @throws Exception - an exception
   */
  @Override
  public final synchronized void release() throws Exception {
    this.beans.clear();
    this.fctConf.release();
  }

  //Request handlers:
  /**
   * <p>Lazy getter HndI18nRq.</p>
   * @param pRqVs request scoped vars
   * @return HndI18nRq
   * @throws Exception - an exception
   */
  private HndI18nRq<RS> lazHndI18nRq(
    final Map<String, Object> pRqVs) throws Exception {
    @SuppressWarnings("unchecked")
    HndI18nRq<RS> rz = (HndI18nRq<RS>) this.beans
      .get(HndI18nRq.class.getSimpleName());
    if (rz == null) {
      rz = new HndI18nRq<RS>();
      rz.setOrm(lazOrm(pRqVs));
      @SuppressWarnings("unchecked")
      IRdb<RS> rdb = (IRdb<RS>) laz(pRqVs, IRdb.class.getSimpleName());
      rz.setRdb(rdb);
      rz.setLog(lazLogStd(pRqVs));
      this.beans.put(HndI18nRq.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HndI18nRq.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  //Database full copy:
  /**
   * <p>Lazy getter RpEntReadXmlDbCp.</p>
   * @param pRqVs request scoped vars
   * @return RpEntReadXmlDbCp
   * @throws Exception - an exception
   */
  private RpEntReadXml lazRpEntReadXmlDbCp(
    final Map<String, Object> pRqVs) throws Exception {
    RpEntReadXml rz = (RpEntReadXml) this.beans.get(ENRDDBCPNM);
    if (rz == null) {
      rz = new RpEntReadXml();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgDbCp(pRqVs));
      rz.setHldFilFdNms(lazHldNmFilFdStDbCp(pRqVs));
      rz.setUtlXml(lazUtlXml(pRqVs));
      rz.setFctFilFld(lazFctNmFilFd(pRqVs));
      this.beans.put(ENWRDBCPNM, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), ENRDDBCPNM
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter RpEntWriXmlDbCp.</p>
   * @param pRqVs request scoped vars
   * @return RpEntWriXmlDbCp
   * @throws Exception - an exception
   */
  private RpEntWriXml lazRpEntWriXmlDbCp(
    final Map<String, Object> pRqVs) throws Exception {
    RpEntWriXml rz = (RpEntWriXml) this.beans.get(ENWRDBCPNM);
    if (rz == null) {
      rz = new RpEntWriXml();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgDbCp(pRqVs));
      rz.setHldGets(lazHldGets(pRqVs));
      rz.setHldNmFdCn(lazHldNmCnToStXml(pRqVs));
      rz.setFctCnvFld(lazFctNmCnToSt(pRqVs));
      this.beans.put(ENWRDBCPNM, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), ENWRDBCPNM
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter DB copy Setng.</p>
   * @param pRqVs request scoped vars
   * @return Setng
   * @throws Exception - an exception
   */
  private Setng lazStgDbCp(final Map<String, Object> pRqVs) throws Exception {
    Setng rz = (Setng) this.beans.get(STGDBCPNM);
    if (rz == null) {
      rz = new Setng();
      rz.setDir(getStgDbCpDir());
      rz.setReflect(lazReflect(pRqVs));
      rz.setUtlPrp(lazUtlPrp(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setLog(lazLogStd(pRqVs));
      this.beans.put(STGDBCPNM, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), STGDBCPNM
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter DBCP HldNmFilFdSt.</p>
   * @param pRqVs request scoped vars
   * @return HldNmFilFdSt
   * @throws Exception - an exception
   */
  private HldNmFilFdSt lazHldNmFilFdStDbCp(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmFilFdSt rz = (HldNmFilFdSt) this.beans
      .get(HLFILFDNMDBCP);
    if (rz == null) {
      rz = new HldNmFilFdSt();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setFilHasIdNm(FctNmFilFdSt.FILHSIDSTDBCPNM);
      rz.setFilSmpNm(FctNmFilFdSt.FILSMPSTDBCPNM);
      rz.setSetng(lazStgDbCp(pRqVs));
      this.beans.put(HLFILFDNMDBCP, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        HLFILFDNMDBCP + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldNmCnToStXml.</p>
   * @param pRqVs request scoped vars
   * @return HldNmCnToStXml
   * @throws Exception - an exception
   */
  private HldNmCnToStXml lazHldNmCnToStXml(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmCnToStXml rz = (HldNmCnToStXml) this.beans
      .get(HldNmCnToStXml.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmCnToStXml();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setCnHsIdToStNm(FctNmCnToSt.CNHSIDSTDBCPNM);
      this.beans.put(HldNmCnToStXml.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldNmCnToStXml.class
        .getSimpleName() + " has been created.");
    }
    return rz;
  }

  //Shared replication services:
  /**
   * <p>Lazy getter HldNmCnFrStXml.</p>
   * @param pRqVs request scoped vars
   * @return HldNmCnFrStXml
   * @throws Exception - an exception
   */
  private HldNmCnFrStXml lazHldNmCnFrStXml(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmCnFrStXml rz = (HldNmCnFrStXml) this.beans
      .get(HldNmCnFrStXml.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmCnFrStXml();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      this.beans.put(HldNmCnFrStXml.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldNmCnFrStXml.class
        .getSimpleName() + " has been created.");
    }
    return rz;
  }

  //ORM:
  /**
   * <p>Lazy getter Orm.</p>
   * @param pRqVs request scoped vars
   * @return Orm
   * @throws Exception - an exception
   */
  private Orm<RS> lazOrm(final Map<String, Object> pRqVs) throws Exception {
    @SuppressWarnings("unchecked")
    Orm<RS> rz = (Orm<RS>) this.beans.get(IOrm.class.getSimpleName());
    if (rz == null) {
      rz = new Orm<RS>();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgOrm(pRqVs));
      @SuppressWarnings("unchecked")
      IRdb<RS> rdb = (IRdb<RS>) laz(pRqVs, IRdb.class.getSimpleName());
      rz.setIsAndr(this.isAndr);
      rz.setNewDbId(this.newDbId);
      rz.setRdb(rdb);
      rz.setSqlQu(lazSqlQu(pRqVs));
      rz.setSrvClVl(lazSrvClVl(pRqVs));
      rz.setFilEntRs(lazFilEntRs(pRqVs));
      rz.setFilCvEn(lazFilCvEnt(pRqVs));
      FctFctEnt fctFctEnt = lazFctFctEnt(pRqVs);
      fctFctEnt.setOrm(rz);
      rz.setFctFctEnt(fctFctEnt);
      //initialization must be by the first invoker (servlet)
      this.beans.put(IOrm.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), Orm.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter Setng ORM.</p>
   * @param pRqVs request scoped vars
   * @return Setng ORM
   * @throws Exception - an exception
   */
  private Setng lazStgOrm(final Map<String, Object> pRqVs) throws Exception {
    Setng rz = (Setng) this.beans.get(STGORMNM);
    if (rz == null) {
      rz = new Setng();
      rz.setDir(getStgOrmDir());
      rz.setReflect(lazReflect(pRqVs));
      rz.setUtlPrp(lazUtlPrp(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setLog(lazLogStd(pRqVs));
      this.beans.put(STGORMNM, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), STGORMNM + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter SrvClVl.</p>
   * @param pRqVs request scoped vars
   * @return SrvClVl
   * @throws Exception - an exception
   */
  private SrvClVl lazSrvClVl(
    final Map<String, Object> pRqVs) throws Exception {
    SrvClVl rz = (SrvClVl) this.beans.get(SrvClVl.class.getSimpleName());
    if (rz == null) {
      rz = new SrvClVl();
      rz.setSetng(lazStgOrm(pRqVs));
      this.beans.put(SrvClVl.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), SrvClVl.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter SqlQu.</p>
   * @param pRqVs request scoped vars
   * @return SqlQu
   * @throws Exception - an exception
   */
  private SqlQu lazSqlQu(
    final Map<String, Object> pRqVs) throws Exception {
    SqlQu rz = (SqlQu) this.beans.get(ISqlQu.class.getSimpleName());
    if (rz == null) {
      rz = new SqlQu();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgOrm(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setHldGets(lazHldGets(pRqVs));
      this.beans.put(ISqlQu.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), SqlQu.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FilCvEnt.</p>
   * @param pRqVs request scoped vars
   * @return FilCvEnt
   * @throws Exception - an exception
   */
  private FilCvEnt<IHasId<?>, ?> lazFilCvEnt(
    final Map<String, Object> pRqVs) throws Exception {
    @SuppressWarnings("unchecked")
    FilCvEnt<IHasId<?>, ?> rz = (FilCvEnt<IHasId<?>, ?>) this.beans
      .get(FilCvEnt.class.getSimpleName());
    if (rz == null) {
      rz = new FilCvEnt();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgOrm(pRqVs));
      rz.setHldFilFdNms(lazHldFilFdCv(pRqVs));
      rz.setFctFilFld(lazFctFilFdCv(pRqVs));
      this.beans.put(FilCvEnt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FilCvEnt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FilEntRs.</p>
   * @param pRqVs request scoped vars
   * @return FilEntRs
   * @throws Exception - an exception
   */
  private FilEntRs<RS> lazFilEntRs(
    final Map<String, Object> pRqVs) throws Exception {
    FilEntRs<RS> rz = (FilEntRs<RS>) this.beans
      .get(FilEntRs.class.getSimpleName());
    if (rz == null) {
      rz = new FilEntRs<RS>();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgOrm(pRqVs));
      rz.setHldFilFdNms(lazHldNmFilFdRs(pRqVs));
      FctNmFilFdRs<RS> fffd = lazFctNmFilFdRs(pRqVs);
      fffd.setFilEnt(rz);
      rz.setFctFilFld(fffd);
      this.beans.put(FilEntRs.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FilEntRs.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldCnvFdCv.</p>
   * @param pRqVs request scoped vars
   * @return HldCnvFdCv
   * @throws Exception - an exception
   */
  private HldCnvFdCv lazHldCnvFdCv(
    final Map<String, Object> pRqVs) throws Exception {
    HldCnvFdCv rz = (HldCnvFdCv) this.beans
      .get(HldCnvFdCv.class.getSimpleName());
    if (rz == null) {
      rz = new HldCnvFdCv();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      this.beans.put(HldCnvFdCv.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        HldCnvFdCv.class.getSimpleName() + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldNmFilFdRs.</p>
   * @param pRqVs request scoped vars
   * @return HldNmFilFdRs
   * @throws Exception - an exception
   */
  private HldNmFilFdRs lazHldNmFilFdRs(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmFilFdRs rz = (HldNmFilFdRs) this.beans
      .get(HldNmFilFdRs.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmFilFdRs();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      this.beans.put(HldNmFilFdRs.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        HldNmFilFdRs.class.getSimpleName() + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldFilFdCv.</p>
   * @param pRqVs request scoped vars
   * @return HldFilFdCv
   * @throws Exception - an exception
   */
  private HldFilFdCv lazHldFilFdCv(
    final Map<String, Object> pRqVs) throws Exception {
    HldFilFdCv rz = (HldFilFdCv) this.beans
      .get(HldFilFdCv.class.getSimpleName());
    if (rz == null) {
      rz = new HldFilFdCv();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      this.beans.put(HldFilFdCv.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldFilFdCv.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldNmCnFrRs.</p>
   * @param pRqVs request scoped vars
   * @return HldNmCnFrRs
   * @throws Exception - an exception
   */
  private HldNmCnFrRs lazHldNmCnFrRs(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmCnFrRs rz = (HldNmCnFrRs) this.beans
      .get(HldNmCnFrRs.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmCnFrRs();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      this.beans.put(HldNmCnFrRs.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldNmCnFrRs.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctCnvCv.</p>
   * @param pRqVs request scoped vars
   * @return FctCnvCv
   * @throws Exception - an exception
   */
  private FctCnvCv lazFctCnvCv(
    final Map<String, Object> pRqVs) throws Exception {
    FctCnvCv rz = (FctCnvCv) this.beans
      .get(FctCnvCv.class.getSimpleName());
    if (rz == null) {
      rz = new FctCnvCv();
      rz.setLogStd(lazLogStd(pRqVs));
      rz.setSqlEsc(lazSqlEsc(pRqVs));
      this.beans.put(FctCnvCv.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FctCnvCv.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctNmCnFrRs.</p>
   * @param pRqVs request scoped vars
   * @return FctNmCnFrRs
   * @throws Exception - an exception
   */
  private FctNmCnFrRs<RS> lazFctNmCnFrRs(
    final Map<String, Object> pRqVs) throws Exception {
    @SuppressWarnings("unchecked")
    FctNmCnFrRs<RS> rz = (FctNmCnFrRs<RS>) this.beans
      .get(FctNmCnFrRs.class.getSimpleName());
    if (rz == null) {
      rz = new FctNmCnFrRs<RS>();
      rz.setLogStd(lazLogStd(pRqVs));
      this.beans.put(FctNmCnFrRs.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FctNmCnFrRs.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctFilFdCv. Mutual dependency with FilEntRs.</p>
   * @param pRqVs request scoped vars
   * @return FctFilFdCv
   * @throws Exception - an exception
   */
  private FctFilFdCv lazFctFilFdCv(
    final Map<String, Object> pRqVs) throws Exception {
    FctFilFdCv rz = (FctFilFdCv) this.beans
      .get(FctFilFdCv.class.getSimpleName());
    if (rz == null) {
      rz = new FctFilFdCv();
      rz.setLogStd(lazLogStd(pRqVs));
      rz.setSetng(lazStgOrm(pRqVs));
      rz.setHldGets(lazHldGets(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setHldNmFdCn(lazHldCnvFdCv(pRqVs));
      rz.setFctCnvFld(lazFctCnvCv(pRqVs));
      rz.setHldFilFdNms(lazHldFilFdCv(pRqVs));
      this.beans.put(FctFilFdCv.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        FctFilFdCv.class.getSimpleName() + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctNmFilFdRs. Mutual dependency with FilEntRs.</p>
   * @param pRqVs request scoped vars
   * @return FctNmFilFdRs
   * @throws Exception - an exception
   */
  private FctNmFilFdRs<RS> lazFctNmFilFdRs(
    final Map<String, Object> pRqVs) throws Exception {
    @SuppressWarnings("unchecked")
    FctNmFilFdRs<RS> rz = (FctNmFilFdRs<RS>) this.beans
      .get(FctNmFilFdRs.class.getSimpleName());
    if (rz == null) {
      rz = new FctNmFilFdRs<RS>();
      rz.setLogStd(lazLogStd(pRqVs));
      rz.setHldSets(lazHldSets(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setHldNmFdCn(lazHldNmCnFrRs(pRqVs));
      rz.setFctCnvFld(lazFctNmCnFrRs(pRqVs));
      this.beans.put(FctNmFilFdRs.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        FctNmFilFdRs.class.getSimpleName() + " has been created.");
    }
    return rz;
  }

  //UVD:
  /**
   * <p>Lazy getter Setng.</p>
   * @param pRqVs request scoped vars
   * @return Setng
   * @throws Exception - an exception
   */
  private Setng lazStgUvd(final Map<String, Object> pRqVs) throws Exception {
    Setng rz = (Setng) this.beans.get(STGUVDNM);
    if (rz == null) {
      rz = new Setng();
      rz.setDir(getStgUvdDir());
      rz.setReflect(lazReflect(pRqVs));
      rz.setUtlPrp(lazUtlPrp(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setLog(lazLogStd(pRqVs));
      this.beans.put(STGUVDNM, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), STGUVDNM + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FilEntRq.</p>
   * @param pRqVs request scoped vars
   * @return FilEntRq
   * @throws Exception - an exception
   */
  private FilEntRq lazFilEntRq(
    final Map<String, Object> pRqVs) throws Exception {
    FilEntRq rz = (FilEntRq) this.beans
      .get(FilEntRq.class.getSimpleName());
    if (rz == null) {
      rz = new FilEntRq();
      rz.setLog(lazLogStd(pRqVs));
      rz.setSetng(lazStgUvd(pRqVs));
      rz.setHldFilFdNms(lazHldNmFilFdStUvd(pRqVs));
      rz.setFctFilFld(lazFctNmFilFd(pRqVs));
      this.beans.put(FilEntRq.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FilEntRq.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter UVD HldNmFilFdSt.</p>
   * @param pRqVs request scoped vars
   * @return HldNmFilFdSt
   * @throws Exception - an exception
   */
  private HldNmFilFdSt lazHldNmFilFdStUvd(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmFilFdSt rz = (HldNmFilFdSt) this.beans
      .get(HLFILFDNMUVD);
    if (rz == null) {
      rz = new HldNmFilFdSt();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setFilHasIdNm(FctNmFilFdSt.FILHSIDSTUVDNM);
      rz.setFilSmpNm(FctNmFilFdSt.FILSMPSTUVDNM);
      rz.setSetng(lazStgUvd(pRqVs));
      this.beans.put(HLFILFDNMUVD, rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        HLFILFDNMUVD + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldNmCnFrSt.</p>
   * @param pRqVs request scoped vars
   * @return HldNmCnFrSt
   * @throws Exception - an exception
   */
  private HldNmCnFrSt lazHldNmCnFrSt(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmCnFrSt rz = (HldNmCnFrSt) this.beans
      .get(HldNmCnFrSt.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmCnFrSt();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setSetng(lazStgUvd(pRqVs));
      this.beans.put(HldNmCnFrSt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldNmCnFrSt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldNmCnToSt.</p>
   * @param pRqVs request scoped vars
   * @return HldNmCnToSt
   * @throws Exception - an exception
   */
  private HldNmCnToSt lazHldNmCnToSt(
    final Map<String, Object> pRqVs) throws Exception {
    HldNmCnToSt rz = (HldNmCnToSt) this.beans
      .get(HldNmCnToSt.class.getSimpleName());
    if (rz == null) {
      rz = new HldNmCnToSt();
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setCnHsIdToStNm(FctNmCnToSt.CNHSIDSTUVDNM);
      rz.setSetng(lazStgUvd(pRqVs));
      this.beans.put(HldNmCnToSt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldNmCnToSt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctNmCnFrSt.</p>
   * @param pRqVs request scoped vars
   * @return FctNmCnFrSt
   * @throws Exception - an exception
   */
  private FctNmCnFrSt lazFctNmCnFrSt(
    final Map<String, Object> pRqVs) throws Exception {
    FctNmCnFrSt rz = (FctNmCnFrSt) this.beans
      .get(FctNmCnFrSt.class.getSimpleName());
    if (rz == null) {
      rz = new FctNmCnFrSt();
      rz.setLogStd(lazLogStd(pRqVs));
      rz.setUtlXml(lazUtlXml(pRqVs));
      this.beans.put(FctNmCnFrSt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FctNmCnFrSt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctNmFilFdSt.</p>
   * @param pRqVs request scoped vars
   * @return FctNmFilFdSt
   * @throws Exception - an exception
   */
  private FctNmFilFdSt lazFctNmFilFd(
    final Map<String, Object> pRqVs) throws Exception {
    FctNmFilFdSt rz = (FctNmFilFdSt) this.beans
      .get(FctNmFilFdSt.class.getSimpleName());
    if (rz == null) {
      rz = new FctNmFilFdSt();
      rz.setLogStd(lazLogStd(pRqVs));
      rz.setHldSets(lazHldSets(pRqVs));
      rz.setStgUvd(lazStgUvd(pRqVs));
      rz.setStgDbCp(lazStgDbCp(pRqVs));
      rz.setHldFdCls(lazHldFldCls(pRqVs));
      rz.setHldNmFdCnUvd(lazHldNmCnFrSt(pRqVs));
      rz.setHldNmFdCnDbCp(lazHldNmCnFrStXml(pRqVs));
      rz.setFctCnvFld(lazFctNmCnFrSt(pRqVs));
      rz.setHldFilFdNmsUvd(lazHldNmFilFdStUvd(pRqVs));
      rz.setHldFilFdNmsDbCp(lazHldNmFilFdStDbCp(pRqVs));
      this.beans.put(FctNmFilFdSt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(),
        FctNmFilFdSt.class.getSimpleName() + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctNmCnToSt.</p>
   * @param pRqVs request scoped vars
   * @return FctNmCnToSt
   * @throws Exception - an exception
   */
  private FctNmCnToSt lazFctNmCnToSt(
    final Map<String, Object> pRqVs) throws Exception {
    FctNmCnToSt rz = (FctNmCnToSt) this.beans
      .get(FctNmCnToSt.class.getSimpleName());
    if (rz == null) {
      rz = new FctNmCnToSt();
      rz.setUtlXml(lazUtlXml(pRqVs));
      rz.setNumStr(lazNumStr(pRqVs));
      rz.setHldNmFdCn(lazHldNmCnToSt(pRqVs));
      rz.setHldGets(lazHldGets(pRqVs));
      rz.setStgUvd(lazStgUvd(pRqVs));
      rz.setStgDbCp(lazStgDbCp(pRqVs));
      rz.setLogStd(lazLogStd(pRqVs));
      this.beans.put(FctNmCnToSt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FctNmCnToSt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  //Common parts:
  /**
   * <p>Lazy getter HldSets.</p>
   * @param pRqVs request scoped vars
   * @return HldSets
   * @throws Exception - an exception
   */
  private HldSets lazHldSets(final Map<String, Object> pRqVs) throws Exception {
    HldSets rz = (HldSets) this.beans
      .get(HldSets.class.getSimpleName());
    if (rz == null) {
      rz = new HldSets();
      rz.setReflect(lazReflect(pRqVs));
      this.beans.put(HldSets.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldSets.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldGets.</p>
   * @param pRqVs request scoped vars
   * @return HldGets
   * @throws Exception - an exception
   */
  private HldGets lazHldGets(final Map<String, Object> pRqVs) throws Exception {
    HldGets rz = (HldGets) this.beans
      .get(HldGets.class.getSimpleName());
    if (rz == null) {
      rz = new HldGets();
      rz.setReflect(lazReflect(pRqVs));
      this.beans.put(HldGets.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldGets.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter HldFldCls.</p>
   * @param pRqVs request scoped vars
   * @return HldFldCls
   * @throws Exception - an exception
   */
  private HldFldCls lazHldFldCls(
    final Map<String, Object> pRqVs) throws Exception {
    HldFldCls rz = (HldFldCls) this.beans
      .get(HldFldCls.class.getSimpleName());
    if (rz == null) {
      rz = new HldFldCls();
      rz.setReflect(lazReflect(pRqVs));
      this.beans.put(HldFldCls.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), HldFldCls.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter FctFctEnt IT DEPENDS OF ORM!!</p>
   * @param pRqVs request scoped vars
   * @return FctFctEnt
   * @throws Exception - an exception
   */
  private FctFctEnt lazFctFctEnt(
    final Map<String, Object> pRqVs) throws Exception {
    FctFctEnt rz = (FctFctEnt) this.beans.get(FctFctEnt.class.getSimpleName());
    if (rz == null) {
      rz = new FctFctEnt();
      this.beans.put(FctFctEnt.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), FctFctEnt.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter UtlPrp.</p>
   * @param pRqVs request scoped vars
   * @return UtlPrp
   * @throws Exception - an exception
   */
  private UtlPrp lazUtlPrp(final Map<String, Object> pRqVs) throws Exception {
    UtlPrp rz = (UtlPrp) this.beans.get(UtlPrp.class.getSimpleName());
    if (rz == null) {
      rz = new UtlPrp();
      this.beans.put(UtlPrp.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), UtlPrp.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter NumStr.</p>
   * @param pRqVs request scoped vars
   * @return NumStr
   * @throws Exception - an exception
   */
  private NumStr lazNumStr(final Map<String, Object> pRqVs) throws Exception {
    NumStr rz = (NumStr) this.beans.get(INumStr.class.getSimpleName());
    if (rz == null) {
      rz = new NumStr();
      this.beans.put(INumStr.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), INumStr.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter SqlEsc.</p>
   * @param pRqVs request scoped vars
   * @return SqlEsc
   * @throws Exception - an exception
   */
  private SqlEsc lazSqlEsc(final Map<String, Object> pRqVs) throws Exception {
    SqlEsc rz = (SqlEsc) this.beans.get(ISqlEsc.class.getSimpleName());
    if (rz == null) {
      rz = new SqlEsc();
      this.beans.put(ISqlEsc.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), ISqlEsc.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter UtlXml.</p>
   * @param pRqVs request scoped vars
   * @return UtlXml
   * @throws Exception - an exception
   */
  private UtlXml lazUtlXml(final Map<String, Object> pRqVs) throws Exception {
    UtlXml rz = (UtlXml) this.beans.get(IUtlXml.class.getSimpleName());
    if (rz == null) {
      rz = new UtlXml();
      this.beans.put(IUtlXml.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), IUtlXml.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter Reflect.</p>
   * @param pRqVs request scoped vars
   * @return Reflect
   * @throws Exception - an exception
   */
  private Reflect lazReflect(final Map<String, Object> pRqVs) throws Exception {
    Reflect rz = (Reflect) this.beans.get(IReflect.class.getSimpleName());
    if (rz == null) {
      rz = new Reflect();
      this.beans.put(IReflect.class.getSimpleName(), rz);
      lazLogStd(pRqVs).info(pRqVs, getClass(), IReflect.class.getSimpleName()
        + " has been created.");
    }
    return rz;
  }

  /**
   * <p>Lazy getter Log.</p>
   * @param pRqVs request scoped vars
   * @return Log
   * @throws Exception - an exception
   */
  private ILog lazLogStd(final Map<String, Object> pRqVs) throws Exception {
    if (this.logStd == null) {
      this.logStd = (ILog) this.fctConf.crePut(pRqVs, LOGSTDNM, this);
    }
    return this.logStd;
  }

  //Simple getters and setters:
  /**
   * <p>Getter for fctConf.</p>
   * @return IFctNm
   **/
  public final synchronized IFctAux getFctConf() {
    return this.fctConf;
  }

  /**
   * <p>Setter for fctConf.</p>
   * @param pFctConf reference
   **/
  public final synchronized void setFctConf(final IFctAux pFctConf) {
    this.fctConf = pFctConf;
  }

  /**
   * <p>Getter for stgDbCpDir.</p>
   * @return String
   **/
  public final String getStgDbCpDir() {
    return this.stgDbCpDir;
  }

  /**
   * <p>Setter for stgDbCpDir.</p>
   * @param pStgDbCpDir reference
   **/
  public final void setStgDbCpDir(final String pStgDbCpDir) {
    this.stgDbCpDir = pStgDbCpDir;
  }

  /**
   * <p>Getter for stgOrmDir.</p>
   * @return String
   **/
  public final String getStgOrmDir() {
    return this.stgOrmDir;
  }

  /**
   * <p>Setter for stgOrmDir.</p>
   * @param pStgOrmDir reference
   **/
  public final void setStgOrmDir(final String pStgOrmDir) {
    this.stgOrmDir = pStgOrmDir;
  }

  /**
   * <p>Getter for stgUvdDir.</p>
   * @return String
   **/
  public final String getStgUvdDir() {
    return this.stgUvdDir;
  }

  /**
   * <p>Setter for stgUvdDir.</p>
   * @param pStgUvdDir reference
   **/
  public final void setStgUvdDir(final String pStgUvdDir) {
    this.stgUvdDir = pStgUvdDir;
  }

  /**
   * <p>Getter for isAndr.</p>
   * @return boolean
   **/
  public final boolean getIsAndr() {
    return this.isAndr;
  }

  /**
   * <p>Setter for isAndr.</p>
   * @param pIsAndr reference
   **/
  public final void setIsAndr(final boolean pIsAndr) {
    this.isAndr = pIsAndr;
  }

  /**
   * <p>Getter for newDbId.</p>
   * @return int
   **/
  public final int getNewDbId() {
    return this.newDbId;
  }

  /**
   * <p>Setter for newDbId.</p>
   * @param pNewDbId reference
   **/
  public final void setNewDbId(final int pNewDbId) {
    this.newDbId = pNewDbId;
  }
}
